version: "3.7"
services: 
  react-app:
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - ./src:/app/src
    environment: 
      - WATCHPACK_POLLING=true
      - REACT_APP_NAME=Knowledge Management AI